# Generated by Django 5.2.4 on 2025-08-08 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL)),
                ('hr', models.ForeignKey(limit_choices_to={'user_type': 'hr'}, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['date'],
            },
        ),
    ]
