# Generated by Django 5.2.4 on 2025-08-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('communication', 'Communication Skills'), ('problem_solving', 'Problem Solving')], max_length=50)),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hr', models.ForeignKey(limit_choices_to={'user_type': 'hr'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
