# Generated by Django 5.2.4 on 2025-08-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobregistration'),
    ]

    operations = [
    ]
